max_steps = 40
output_dir = "outputs/qwen3-1.7b-puzzle-sft"

[ckpt]

[model]
name = "PrimeIntellect/Qwen3-1.7B"

[data]
name = "saad1926q/15-puzzle"
subsets = ["sft"]
splits = ["sft"]
seq_len = 3072
batch_size = 16
micro_batch_size = 1
pack_function = "cat"
shuffle = true
seed = 42

[optim]
lr = 1e-5

[deployment]
type = "single_node"
num_gpus = 1
